version: '3'
services:
  #Очереди
  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
    env_file: .env
    environment:
       - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
       - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  #mysql вторая папка для тестовой базы
  mysql:
    image: 'mysql:5.7'
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
    - ${MYSQL_PATH}:/var/lib/mysql/
    - ${MYSQL_DUMP_FILES}:/usr/local/test-base/
    ports:
    - "3306:3306"

  #nginx без изменений
  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        USER: ${NGINX_USER}
        DOMAIN: ${NGINX_DOMAIN}
    volumes:
      - ./..:/var/www/html/HomeAccountingLaravel
    ports:
    - "80:80"
    - "443:443"
    env_file: .env
    depends_on:
      - fpm

  #Настроенный fpm со всеми либами
  fpm:
    env_file: .env
    build:
      context: php
      dockerfile: Dockerfile
      args:
        USER: ${FPM_USER}
    volumes:
      - ./..:/var/www/html/HomeAccountingLaravel/
    expose:
      - 9000
    depends_on:
      - mysql
      - rabbit
