version: '3'
services:

  #Очереди
  rabbit:
    image: rabbitmq:3.7-management
    ports:
    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  #mysql вторая папка для тестовой базы
  mysql:
    image: 'mysql:5.7'
    restart: always
    volumes:
    - '~/mysql-test/:/var/lib/mysql/'
    - './mysql/test-base/:/usr/local/test-base/'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounting
    ports:
    - "3306:3306" #Для клиентов
    #command: mysql -u root -proot accounting < /usr/local/test-base/accounting.sql #просто чтобы записать команду для развертывания тестовой базы

  #nginx без изменений
  nginx:
    image: "nginx:latest"
    restart: always
    volumes:
      - './nginx/conf.d/:/etc/nginx/conf.d/'
      - '../:/var/www/html/HomeAccountingLaravel'
    ports:
    - "80:80"
    - "443:443"
    depends_on:
      - fpm
      - mysql

  #Настроенный fpm со всеми либами
  fpm:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    volumes:
      - '/var/www/html/HomeAccountingLaravel/:/var/www/html/HomeAccountingLaravel/'
      - './fpm/supervisor/conf.d/:/var/www/html/HomeAccountingLaravel'
    depends_on:
      - mysql
      - rabbit
    environment:
      USER: dastanaron