FROM nginx:1.21.6

COPY nginx.conf /etc/nginx/
RUN sed -i -e "s/{USER}/root/g" /etc/nginx/nginx.conf

COPY conf.d/default.conf /etc/nginx/conf.d/
COPY conf.d/accounting.prod.conf /etc/nginx/conf.d/

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
